FROM node:14

WORKDIR /usr/src/app/client

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./


RUN npm install --silent
USER node
COPY --chown=node:node . .

EXPOSE 3000

# start app
CMD ["npm", "start"]