version: '3'
services:
  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app/server
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/src/app/client

volumes:
  pg_data: